### ISSUE TITLE
Create presentation slides

### ISSUE THREAD

**Issue by samuell** [AfricArxiv/africarxiv.github.io#5]

**Comment by johav** [comment]
I started a Google Sliedes file at https://docs.google.com/presentation/d/1K6dLKk7pB9hE-U3S_V5UuoFJfINKp6BrOqDq2QAmA28/
Feel free to start working on it. We could do something similar to the presentation at https://paleorxiv.github.io/ and come up with our own contents

**Comment by johav** [comment]
What we need to cover - and maybe in this particular order:

- [ ] Welcome to Africarxiv

- [ ] Who is our target group?

- [ ] What is a preprint?

- [ ] how to submit your own research for inclusion in the AfricArXiv collection 

- [ ] advantages that doing so can bring in terms of wider sharing of knowledge and an increased opportunity to build collaborations in and outside of Africa

Compare / adapt from the pres on https://paleorxiv.github.io/ (let's make sure to cite/reference in the last slide)
