### ISSUE TITLE
Newsletter

### ISSUE THREAD

**Issue by johav** [AfricArxiv/africarxiv.github.io#6]
was just inspired by paleorxiv's tinyletter by mailchimp. 
Better options?

Do we need a newsletter at all / at this stage?
Maybe good to actually have a form where people can subscribe (Google Form?) to occasionally be informed about updates and announcements on AfricArxiv - excl. new submissions

**Comment by samuell** [comment]
I think a mailing list is a good idea, as it lessens the reliance on social media, which is not always a sure way to actually get the news, because of more and more algorithms involved.

I have only used MailChimp, but it works pretty well.

**Comment by samuell** [comment]
@johav What address should we use as a sender address, as well as account login for mailchimp? Perhaps it'd be good with a mail forwarder to three of us, something like newsletter@africarxiv.org?

**Comment by johav** [comment]
info@africarxiv.org :)
Giving you the admin access

**Comment by samuell** [comment]
Added now! (closing the issue).

![selection_990](https://user-images.githubusercontent.com/125003/45704420-23261200-bb77-11e8-81bb-0707a7d28e9c.png)
