### ISSUE TITLE
Resources

### ISSUE THREAD

**Issue by johav** [AfricArxiv/africarxiv.github.io#8]
A list of further resources on Open Access for Research in Africa

- http://www.unesco.org/new/en/communication-and-information/portals-and-platforms/goap/access-by-region/africa/ 
- https://riojournal.com/

**Comment by samuell** [comment]
Is this supposed to be a broad list of links to open science initiatives in, or related Africa?

What about links like these (to be filled with more similar links across disciplines and countries though, of course)?:

- [Bridging Biobanking and Biomedical Research Across Europe and Africa](http://www.b3africa.org)
- [Open Knowledge Ethiopia](http://okfneth.blogspot.com/_

**Comment by johav** [comment]
Absolutely! We can also have it as a gDoc so that people can feed in and extend on the list.
How is this? 
https://docs.google.com/spreadsheets/d/1rLtrKZVZUnvM1Pu7OTfa_l8WLBZqgNjs-TRVwlhkz3I/

**Comment by johav** [comment]
Africa
- [The African Open Science Platform](https://zenodo.org/record/1407488#.W-8PDXpKjOS)
